server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ms-policy-services
              uri: lb://MS-POLICY-SERVICES
              predicates:
                - Path=/api/v1/policies/**
              filters:
                - StripPrefix=1
#                - AuthenticationFilter

            - id: ms-auth-services-login
              uri: lb://MS-AUTH-SERVICES
              predicates:
                - Path=/api/v1/login
              filters:
                - StripPrefix=1

            - id: ms-auth-services-users
              uri: lb://MS-AUTH-SERVICES
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=1
#                - AuthenticationFilter

            - id: ms-auth-services-insureds
              uri: lb://MS-AUTH-SERVICES
              predicates:
                - Path=/api/v1/insureds/**
              filters:
                - StripPrefix=1
#                - AuthenticationFilter

            - id: ms-protocol-services
              uri: lb://MS-PROTOCOL-SERVICES
              predicates:
                - Path=/api/v1/protocols/**
              filters:
                - StripPrefix=1
#                - AuthenticationFilter

            - id: ms-claims-services
              uri: lb://MS-CLAIMS-SERVICES
              predicates:
                - Path=/api/v1/claims/**
              filters:
                - StripPrefix=1
#                - AuthenticationFilter

            - id: ms-analysis-services
              uri: lb://MS-ANALYSIS-SERVICES
              predicates:
                - Path=/api/v1/analysis/**
              filters:
                - StripPrefix=1
#                - AuthenticationFilter

            - id: ms-claims-questionnaire-services
              uri: lb://MS-CLAIMS-QUESTIONNAIRE-SERVICES
              predicates:
                - Path=/claims/{claimId}/questionnaire/**
              filters:
                - StripPrefix=0
#                - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG