spring:
  application:
    name: ms-auth-services
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userDB}
    username: ${SPRING_DATASOURCE_USERNAME:userDB}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
    locations: classpath:db/migration
  messages:
    basename: messages
    encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${JWT_TOKEN:019f9015-0aa8-7557-b4a2-01589d2b5344}

server:
  port: ${SERVER_PORT:8085}

logging:
  level:
    com.zaxxer.hikari: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    displayRequestDuration: true
